<?php

namespace App\Form;

use App\Entity\QuizKids;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class QuizKidsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('question', TextType::class, [
            'label' => 'Question',
            'required' => true,
            
        ])
        ->add('options', CollectionType::class, [
            'entry_type' => TextType::class,
            'allow_add' => true,
            'allow_delete' => true,
            'prototype' => true,
            'by_reference' => false,
            'label' => false,
            'attr' => ['class' => 'options-collection'],
            'entry_options' => ['attr' => ['class' => 'form-control']],
            'required' => true,
            
        ])
        ->add('correctAnswer', TextType::class, [
            'label' => 'Correct Answer',
            'required' => true,
        ])
        
        ->add('level', ChoiceType::class, [
            'choices' => [
                'Easy' => 'easy',
                'Medium' => 'medium',
                'Hard' => 'hard',
            ],
            'label' => 'Level',
            'required' => true,
        ])
        ->add('genre', ChoiceType::class, [
            'choices' => [
                'Culture génerale' => 'Culture génerale',
                'Géographie' => 'Géographie',
                'Sport' => 'Sport',
                'Sur les animaux' => 'Sur les animaux',
                'Scientifique' => 'Scientifique',
                'Dessin-animé' => 'Dessin-animé',
                
            ],
            'label' => 'Genre',
            'required' => true,
            
        ])
        ->add('mediaFile', FileType::class, [
            'label' => 'Upload Media (image/video)',
            'mapped' => false,
            'required' => false
        ])
        ->add('country', ChoiceType::class, [
            'choices' => [
                'Afghanistan' => 'Afghanistan',
                'Albania' => 'Albania',
                'Algeria' => 'Algeria',
                'Andorra' => 'Andorra',
                'Angola' => 'Angola',
                'Argentina' => 'Argentina',
                'Armenia' => 'Armenia',
                'Australia' => 'Australia',
                'Austria' => 'Austria',
                'Azerbaijan' => 'Azerbaijan',
                'Bahamas' => 'Bahamas',
                'Bahrain' => 'Bahrain',
                'Bangladesh' => 'Bangladesh',
                'Barbados' => 'Barbados',
                'Belarus' => 'Belarus',
                'Belgium' => 'Belgium',
                'Belize' => 'Belize',
                'Benin' => 'Benin',
                'Bhutan' => 'Bhutan',
                'Bolivia' => 'Bolivia',
                'Bosnia and Herzegovina' => 'Bosnia and Herzegovina',
                'Botswana' => 'Botswana',
                'Brazil' => 'Brazil',
                'Brunei' => 'Brunei',
                'Bulgaria' => 'Bulgaria',
                'Burkina Faso' => 'Burkina Faso',
                'Burundi' => 'Burundi',
                'Cabo Verde' => 'Cabo Verde',
                'Cambodia' => 'Cambodia',
                'Cameroon' => 'Cameroon',
                'Canada' => 'Canada',
                'Central African Republic' => 'Central African Republic',
                'Chad' => 'Chad',
                'Chile' => 'Chile',
                'China' => 'China',
                'Colombia' => 'Colombia',
                'Comoros' => 'Comoros',
                'Congo' => 'Congo',
                'Costa Rica' => 'Costa Rica',
                'Croatia' => 'Croatia',
                'Cuba' => 'Cuba',
                'Cyprus' => 'Cyprus',
                'Czech Republic' => 'Czech Republic',
                'Democratic Republic of the Congo' => 'Democratic Republic of the Congo',
                'Denmark' => 'Denmark',
                'Djibouti' => 'Djibouti',
                'Dominica' => 'Dominica',
                'Dominican Republic' => 'Dominican Republic',
                'Ecuador' => 'Ecuador',
                'Egypt' => 'Egypt',
                'El Salvador' => 'El Salvador',
                'Equatorial Guinea' => 'Equatorial Guinea',
                'Eritrea' => 'Eritrea',
                'Estonia' => 'Estonia',
                'Eswatini' => 'Eswatini',
                'Ethiopia' => 'Ethiopia',
                'Fiji' => 'Fiji',
                'Finland' => 'Finland',
                'France' => 'France',
                'Gabon' => 'Gabon',
                'Gambia' => 'Gambia',
                'Georgia' => 'Georgia',
                'Germany' => 'Germany',
                'Ghana' => 'Ghana',
                'Greece' => 'Greece',
                'Grenada' => 'Grenada',
                'Guatemala' => 'Guatemala',
                'Guinea' => 'Guinea',
                'Guinea-Bissau' => 'Guinea-Bissau',
                'Guyana' => 'Guyana',
                'Haiti' => 'Haiti',
                'Honduras' => 'Honduras',
                'Hungary' => 'Hungary',
                'Iceland' => 'Iceland',
                'India' => 'India',
                'Indonesia' => 'Indonesia',
                'Iran' => 'Iran',
                'Iraq' => 'Iraq',
                'Ireland' => 'Ireland',
                'Israel' => 'Israel',
                'Italy' => 'Italy',
                'Ivory Coast' => 'Ivory Coast',
                'Jamaica' => 'Jamaica',
                'Japan' => 'Japan',
                'Jordan' => 'Jordan',
                'Kazakhstan' => 'Kazakhstan',
                'Kenya' => 'Kenya',
                'Kiribati' => 'Kiribati',
                'Korea, North' => 'Korea, North',
                'Korea, South' => 'Korea, South',
                'Kuwait' => 'Kuwait',
                'Kyrgyzstan' => 'Kyrgyzstan',
                'Laos' => 'Laos',
                'Latvia' => 'Latvia',
                'Lebanon' => 'Lebanon',
                'Lesotho' => 'Lesotho',
                'Liberia' => 'Liberia',
                'Libya' => 'Libya',
                'Liechtenstein' => 'Liechtenstein',
                'Lithuania' => 'Lithuania',
                'Luxembourg' => 'Luxembourg',
                'Madagascar' => 'Madagascar',
                'Malawi' => 'Malawi',
                'Malaysia' => 'Malaysia',
                'Maldives' => 'Maldives',
                'Mali' => 'Mali',
                'Malta' => 'Malta',
                'Marshall Islands' => 'Marshall Islands',
                'Mauritania' => 'Mauritania',
                'Mauritius' => 'Mauritius',
                'Mexico' => 'Mexico',
                'Micronesia' => 'Micronesia',
                'Moldova' => 'Moldova',
                'Monaco' => 'Monaco',
                'Mongolia' => 'Mongolia',
                'Montenegro' => 'Montenegro',
                'Morocco' => 'Morocco',
                'Mozambique' => 'Mozambique',
                'Myanmar' => 'Myanmar',
                'Namibia' => 'Namibia',
                'Nauru' => 'Nauru',
                'Nepal' => 'Nepal',
                'Netherlands' => 'Netherlands',
                'New Zealand' => 'New Zealand',
                'Nicaragua' => 'Nicaragua',
                'Niger' => 'Niger',
                'Nigeria' => 'Nigeria',
                'North Macedonia' => 'North Macedonia',
                'Norway' => 'Norway',
                'Oman' => 'Oman',
                'Pakistan' => 'Pakistan',
                'Palau' => 'Palau',
                'Panama' => 'Panama',
                'Papua New Guinea' => 'Papua New Guinea',
                'Paraguay' => 'Paraguay',
                'Peru' => 'Peru',
                'Philippines' => 'Philippines',
                'Poland' => 'Poland',
                'Portugal' => 'Portugal',
                'Qatar' => 'Qatar',
                'Romania' => 'Romania',
                'Russia' => 'Russia',
                'Rwanda' => 'Rwanda',
                'Saint Kitts and Nevis' => 'Saint Kitts and Nevis',
                'Saint Lucia' => 'Saint Lucia',
                'Saint Vincent and the Grenadines' => 'Saint Vincent and the Grenadines',
                'Samoa' => 'Samoa',
                'San Marino' => 'San Marino',
                'Sao Tome and Principe' => 'Sao Tome and Principe',
                'Saudi Arabia' => 'Saudi Arabia',
                'Senegal' => 'Senegal',
                'Serbia' => 'Serbia',
                'Seychelles' => 'Seychelles',
                'Sierra Leone' => 'Sierra Leone',
                'Singapore' => 'Singapore',
                'Slovakia' => 'Slovakia',
                'Slovenia' => 'Slovenia',
                'Solomon Islands' => 'Solomon Islands',
                'Somalia' => 'Somalia',
                'South Africa' => 'South Africa',
                'South Sudan' => 'South Sudan',
                'Spain' => 'Spain',
                'Sri Lanka' => 'Sri Lanka',
                'Sudan' => 'Sudan',
                'Suriname' => 'Suriname',
                'Sweden' => 'Sweden',
                'Switzerland' => 'Switzerland',
                'Syria' => 'Syria',
                'Taiwan' => 'Taiwan',
                'Tajikistan' => 'Tajikistan',
                'Tanzania' => 'Tanzania',
                'Thailand' => 'Thailand',
                'Timor-Leste' => 'Timor-Leste',
                'Togo' => 'Togo',
                'Tonga' => 'Tonga',
                'Trinidad and Tobago' => 'Trinidad and Tobago',
                'Tunisia' => 'Tunisia',
                'Turkey' => 'Turkey',
                'Turkmenistan' => 'Turkmenistan',
                'Tuvalu' => 'Tuvalu',
                'Uganda' => 'Uganda',
                'Ukraine' => 'Ukraine',
                'United Arab Emirates' => 'United Arab Emirates',
                'United Kingdom' => 'United Kingdom',
                'United States' => 'United States',
                'Uruguay' => 'Uruguay',
                'Uzbekistan' => 'Uzbekistan',
                'Vanuatu' => 'Vanuatu',
                'Vatican City' => 'Vatican City',
                'Venezuela' => 'Venezuela',
                'Vietnam' => 'Vietnam',
                'Yemen' => 'Yemen',
                'Zambia' => 'Zambia',
                'Zimbabwe' => 'Zimbabwe',
            ],
            'placeholder' => 'Select a country',
        ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => QuizKids::class,
        ]);
    }
}
